### ISSUE TITLE
Uncaught Error: Expected not to find a document already present for an add

### ISSUE THREAD

**Issue by anubhav756** [abecks/meteor-fast-render#7] opened 2017-08-17 11:25 UTC
![error](https://user-images.githubusercontent.com/12044408/29410103-d22c376e-836c-11e7-9573-11b578af98d0.png)

When server sends an object that is already present on client via fast-render, the client throws this error.

This issue is almost similar to [#49](https://github.com/kadirahq/fast-render/issues/49) of the original repo.

I wonder why the fix for that repo isn't working now.

**Comment by abecks** [comment] 2017-08-17 16:05
I've noticed this is fixed in
https://github.com/theosp/fast-render/commit/990159dcfc31a35b35599c6ed4760aed3ea38c72

I will port the change over today

**Comment by anubhav756** [comment] 2017-08-17 18:34
https://github.com/abecks/meteor-fast-render/pull/8 :slightly_smiling_face:

**Comment by abecks** [comment] 2017-08-17 18:41
Fixed in 2.16.5, thanks!

**Comment by anubhav756** [comment] 2017-08-17 18:47
Cheers! :+1:

**Comment by anubhav756** [comment] 2017-08-17 18:57
Uh oh. There's another error now

![error](https://user-images.githubusercontent.com/12044408/29428755-f2a88512-83ab-11e7-9c9f-a8ab34716ff3.png)

**Comment by abecks** [comment] 2017-08-17 18:58
Hmm, check that other repo by @theosp ? Maybe we missed more fixes

**Comment by anubhav756** [comment] 2017-08-31 11:30
So I finally got my hands dirty, and dug into the code.

Here's a possible fix https://github.com/abecks/meteor-fast-render/pull/10

You might find a better fix, but let's start with this :slightly_smiling_face:

**Comment by abecks** [comment] 2017-08-31 16:38
Good work on this so far. I believe the message coming from the DDP client is one of `added`, `removed` or `changed`. All 3 events can potentially cause this error, they can be found in the `mongo` package in `collection.js`.

I'm wondering if a better solution would be to modify the `mongo` package to not throw errors in these conditions.  I don't really a see a purpose to throwing errors there that would halt the entire application. Surely a `console.error` would be more useful. Thoughts?

**Comment by anubhav756** [comment] 2017-08-31 19:00
Not sure if simply suppressing the error would be 100% correct.

For instance, if you modify a fast rendered value before the actual value is populated in the minimongo, then after the actual data population, not only the error shows up, but there are inconsistencies when you again modify the same, or some other value, which were previously fast rendered.

To help you understand, consider my minimal replication of the issue here http://clicky.now.sh. It is a really minimal app, which increments the number displayed on a button when you click it. Here, all the 3 values in these buttons are fast rendered.

Observe that, when the app fast renders, of you click on any of the buttons, before the DDP conn is made, then after the the conn is made, the error (obviously) shows up. BUT now, click on some other button. You will observe the inconsistencies. Moreover, this operation cannot make you use of the optimistic UI, and the operation takes longer than usual.

That is why, I do not think that just suppressing the error would be ideal.

What do you say?

Regards,
Anubhav Dhawan
Ph: 9582838362

**Comment by anubhav756** [comment] 2017-09-01 07:12
Guess what! I think I found the ideal solution.

Updated the PR https://github.com/abecks/meteor-fast-render/pull/10

I removed the `!serverDoc` condition and everything seems to work like a dream.

I'm not sure why `serverDoc` condition was there, so please review.

Otherwise, it seems to work perfectly now

**Comment by abecks** [comment] 2017-09-05 17:37
I think you may be onto something. I just looked into it and the `serverDoc` condition is populated when the client is simulating a collection change. Interestingly, I'm receiving the errors when my page loads, so the client shouldn't be simulating anything yet. I've thrown in:

```
    var serverDoc = this._getServerDoc(msg.collection, id)
    serverDoc && console.warn('serverDoc', serverDoc)
```

and will monitor for the root cause of the error. The check is there to exclude the simulated collection changes from being transformed from `added` to `changed`. Which could indeed cause the errors if the client is trying to simulate an `add` for a document it already has.

**Comment by abecks** [comment] 2017-09-11 18:48
I've tracked down the cause of the errors that I'm receiving. For me, errors occur when FastRender is trying to add documents that are already populated by the publication, but are not yet in the collection at the time of checking. Its a race condition between the two.

Inside the `Meteor.connection._livedata_data` monkey patch of `ddp_update.js`, the following occurs:

1. A message is received to add document D to collection A
2. The function checks to see if the document already exists in collection A, it does not, and therefore does not transform it to an update query and allows it to continue as an add query
3. A message is received to add document D to collection A, but this time its from FastRender (decorated with frGen=true)
4. The function checks to see if the document already exists in Collection A. It does NOT yet exist in the collection, as we're racing against the outcome of step 2. It again does not transform the query.
5. By the time the system tries to add the second document D, the first one is now present in the collection and throws a `Expected not to find a document already present for an add` error.

So this is happening because the publications are populating the collections before FastRender, and they are essentially racing against each other. The solution is likely going to be to delay any publication writes until FastRender is complete. 

I'm going to try this solution:

1. If a message without `frGen=true` is received while `FastRender._revertedBackToOriginal` is false, queue it for later
2. When we set `FastRender._revertedBackToOriginal` to `true`, apply all the queued DDP messages

**Comment by nadeemja** [comment] 2017-10-06 12:35
Any progress? :)

**Comment by sirpy** [comment] 2017-10-07 19:04
i found out this happens when subscribing to a publication of Meteor.users that include the current logged in user.

**Comment by abecks** [comment] 2018-03-10 01:00
It's much better to just let FastRender load all of the data before you start any real subscriptions. 

On the client:
```
FastRender.wait() // tell fastrender not to start loading the data automatically
InjectData.getData('fast-render-data', async function(data) {
    FastRender.init(data)
    // it is now safe to begin routing/rendering
})
```

**Closed by abecks** 2018-03-10 01:00 UTC
